config/routes.rb
Waluty::Application.routes.draw do
  root :to =>  "pages#index"
  match "/wykres", :to => "pages#wykres"

   

end

app/models/kursy.rb
class Kursy < ActiveRecord::Base
  attr_accessible :data, :kod, :kurs, :nazwa, :przelicznik
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include ApplicationHelper

  def index 
        @wybor_daty = data_wyboru_kursu
        @nazwa = select_nazwa_waluty
        @waluty = waluty_baza("data",params[:set_locale])
          if(params[:set_locale])
             respond_to do |format|
               format.html
               format.js
             end
          elsif(params[:set_name])
             @kursy  = waluty_baza("nazwa",params[:set_name])
             respond_to do |format|
              format.html
              format.js {render :json => @kursy }
             end  
          end
  end

 private 

 def data_wyboru_kursu
      temp = Kursy.find(:all,:select => 'DISTINCT data', 
			   :order => 'data DESC')
      data=[] 
      (0..temp.count-1).each do |f|
          data[f] = temp[f].data
       end
       data
   end
   
 def select_nazwa_waluty
    temp = Kursy.find(:all,:select => 'DISTINCT nazwa',:order => 'nazwa')
   nazwa=[]
    (0..temp.count-1).each do |k|
      nazwa[k] = temp[k].nazwa
    end
    nazwa
 end

   def waluty_baza(key,value)
       txt = key +"= '#{value}'"
       waluty = Kursy.find(:all, :conditions => txt )
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
  require 'xml'
  require 'open-uri'
  require 'xml/libxml'

   def read_url(string)  
      temp_url  = open(string).read 
      source = XML::Parser.string(temp_url)
      content = source.parse  
   end 
####################################################
   def spr_daty
       data_xml = data_kursow
       data_baza = Kursy.find(:all, :select =>'data',
			      :order => 'data DESC', :limit => 1 )[0].data
       if data_xml > data_baza 
          dodaj_kurs
          usun_kurs  
       end
   end
   ############################################
   def url_nbp
     content  = read_url("http://rss.nbp.pl/kursy/TabelaA.xml")
     entries = content.root.find('.//enclosure')
     url = entries.first.attributes.get_attribute('url')
     
     if url.first.value.nil?
        "error"
     else
        "#{url.first.value}" 
     end
   end
   ############################################
   def waluty 
         content  = read_url(url_nbp)
         tabela_walut = content.root.find('.//pozycja') 
   end

   ############################################
   def data_kursow 
       content  = read_url(url_nbp)
       data = content.root.find('.//data_publikacji')
       data.first.content 
   end

   ###################### Baza Danych ####################
   
   ##############################
   def dodaj_kurs
       kursy = waluty
       data = data_kursow  
       kursy.each do |k|
        Kursy.create!(
                      :nazwa => k.find_first("nazwa_waluty").content,
                      :kod =>   k.find_first("kod_waluty").content,
                      :przelicznik => k.find_first("przelicznik").content,
                      :kurs =>	  k.find_first("kurs_sredni").content,
                      :data => data 
                      )
       end
   end
   ################################
   def usun_kurs
       temp_data = Kursy.find(:all,:select=> 'data', 
			      :order => 'data ASC', :limit => 1)[0].data
       Kursy.delete_all ("data '#{temp_data.first.data}'")
   end

   def time 
      t = Time.now
      time = t.strftime('%X')
      time > '13:00:00'
   end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=@title %></title>
  <%= include_gon %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/_table.html.erb
<table id="waluty" class = "display">
  <thead>
   <tr>
     <th>NAZWA</th>
     <th>KOD</th>
     <th>PRZELICZNIK</th>
     <th>CENA ŚREDNIA</th>
   </tr>
  </thead>
  <tbody>
    <% @waluty.each do |w| %>
      <tr>
        <td><%= w.nazwa %></td>
        <td><%= w.kod %></td>
        <td><%= w.przelicznik %></td>
        <td><%= w.kurs %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pages/index.html.erb
 <h1>ŚREDNIE KURSY WALUT NBP</h1>

<div id="nav1">
<ul>
  <li id="z1">ŚREDNIE KURSY WALUT</li>
  <li id="z2">WYKRES ZMIANY KURSU WALUTY</li>
</ul>
</div>
<div id="contener">
  

 <div id="tabela">
 <%= form_tag root_path ,:name=>"data_waluty",
                          :remote => true do %>
	<%= select_tag 'set_locale',
	options_for_select(@wybor_daty,
          :selected =>@wybor_daty.first ),
          :remote => true, 
	  :onchange => '' %>
  <% end %>

  <div id="tab"> <%= render 'table' %></div>
</div>
 <div id="wykres">
  <%= form_tag root_path ,
        :name=>"name_waluty",
        :remote => true do %>
	<%= select_tag 'set_name',
	options_for_select(@nazwa),
        :include_blank =>"none",
	:onchange => 'change_name()' %>
  <% end %>
  <div id="chart"></div>
 </div>

</div >
  

app/views/pages/index.js.erb
$("#tab").html("");
$("#tab").append("<%= escape_javascript(render 'table') %>");
$('#waluty').dataTable({sPaginationType: "full_numbers",bJQueryUI: true}).fnReloadAjax();

app/views/pages/wykres.html.erb
<h1>WYKRES</h1>
<%= link_to "KURSY", root_path,:remote=> false  %>
<div id="chart"style="width:400px; height: 300px;">  </div>

<div id="select_wykres">
<%= form_tag wykres_path ,:name=>"name_waluty",:remote => true do %>
	<%= select_tag 'set_name',
	options_for_select(@nazwa,:selected =>@nazwa.first ),
	:onchange => 'change_name()' %>
  <% end %>
</div>